// ════════════════════════════════════════════════════════════════
// SNS Hospice Solutions — shared clinical form design system
// ════════════════════════════════════════════════════════════════
// Single source of truth for colors + styles used by every clinical
// assessment/visit-note screen (RNICA, CHHA, MSW ICA, SC ICA, ...).
// Do NOT fork or copy these values into a page-specific file — import
// getRnicaColors/getRnicaStyles here so every page stays visually
// identical (same fonts, spacing, card treatment, inputs) and future
// design changes only need to happen in one place.

export function getRnicaColors(mode) {
  if (mode === "light") {
    return {
      navy: "#1E3A5F",
      hope: "#059669",
      sfv: "#DC2626",
      cms: "#2563EB",
      teal: "#0D9488",
      tealDark: "#0F766E",
      dark: "#0F172A",
      gray: "#64748B",
      border: "#D8E3E8",
      bg: "#F8FAFC",
      white: "#FFFFFF",
      warning: "#F59E0B",
      error: "#EF4444",
      success: "#10B981",
      pageBg: "#EEF3F8",
      sidebarBg: "#F8FBFD",
      sidebarItemColor: "#334155",
      sidebarActiveColor: "#0F766E",
      panelBg: "rgba(255,255,255,0.96)",
      inputBg: "#FFFFFF",
      hopeTagBg: "#ECFDF5",
      sfvTagBg: "#FEF2F2",
      cmsTagBg: "#EFF6FF",
      errorBg: "#fee2e2",
      infoBoxBg: "linear-gradient(135deg, #eef6ff, #eefaf8)",
      warningBoxBg: "linear-gradient(135deg, #fffbeb, #fff7ed)",
      successBoxBg: "linear-gradient(135deg, #ecfdf5, #f0fdf4)",
      textOnTeal: "#FFFFFF",
      mapControlBg: "#F8FAFC",
      mapControlBorder: "#E2E8F0",
      mapChipBg: "#FFFFFF",
      mapChipText: "#0F172A",
      mapMuted: "#475569",
      tealBg: "#CCFBF1",
      amberTagBg: "#FFFBEB",
    };
  }
  return {
    navy: "#1E3A5F",
    hope: "#4ade80",
    sfv: "#fb7185",
    cms: "#38bdf8",
    teal: "#35e0c1",
    tealDark: "#5ce9d0",
    dark: "#f8fafc",
    gray: "#a9bcd0",
    border: "rgba(148, 163, 184, 0.16)",
    bg: "#0c1a2b",
    white: "#14263a",
    warning: "#fbbf24",
    error: "#fb7185",
    success: "#4ade80",
    pageBg: "#07111d",
    sidebarBg: "#091525",
    sidebarItemColor: "#a9bcd0",
    sidebarActiveColor: "#35e0c1",
    panelBg: "rgba(20, 38, 58, 0.92)",
    inputBg: "#0d1b2b",
    hopeTagBg: "rgba(74, 222, 128, 0.12)",
    sfvTagBg: "rgba(251, 113, 133, 0.12)",
    cmsTagBg: "rgba(56, 189, 248, 0.12)",
    errorBg: "rgba(251, 113, 133, 0.14)",
    infoBoxBg: "linear-gradient(135deg, rgba(56,189,248,0.14), rgba(53,224,193,0.10))",
    warningBoxBg: "linear-gradient(135deg, rgba(251,191,36,0.16), rgba(251,146,60,0.10))",
    successBoxBg: "linear-gradient(135deg, rgba(74,222,128,0.16), rgba(53,224,193,0.10))",
    textOnTeal: "#031317",
    mapControlBg: "#182c42",
    mapControlBorder: "rgba(148, 163, 184, 0.2)",
    mapChipBg: "#101f31",
    mapChipText: "#f8fafc",
    mapMuted: "#a9bcd0",
    tealBg: "rgba(53, 224, 193, 0.12)",
    amberTagBg: "rgba(251, 191, 36, 0.12)",
  };
}

export function getRnicaStyles(COLORS) {
  return {
    page: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      height: "auto",
      fontFamily: "Inter, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      color: COLORS.dark,
      background: COLORS.pageBg,
    },
    banner: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "8px 16px",
      background: "linear-gradient(90deg, #1E3A5F 0%, #0D9488 100%)",
      color: "#FFFFFF",
      fontSize: 11.5,
      boxShadow: "0 4px 16px rgba(15, 23, 42, 0.12)",
      borderBottom: "1px solid rgba(148, 163, 184, 0.2)",
    },
    bannerName: { fontSize: 14, fontWeight: 800, letterSpacing: "-0.02em" },
    bannerMeta: { fontSize: 10, opacity: 0.82, letterSpacing: "0.01em" },
    workspace: { display: "flex", flex: 1, minHeight: 0, minWidth: 0, overflow: "visible" },
    sidebar: {
      width: 200,
      background: COLORS.sidebarBg,
      borderRight: `1px solid ${COLORS.border}`,
      overflowY: "auto",
      padding: "8px 6px",
      flexShrink: 0,
      minHeight: 0,
    },
    sidebarItem: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      padding: "4px 8px",
      margin: "1px 0",
      fontSize: 11.5,
      cursor: "pointer",
      borderRadius: 6,
      borderLeft: "3px solid transparent",
      transition: "all 0.2s ease",
      color: COLORS.sidebarItemColor,
    },
    sidebarActive: {
      background: "linear-gradient(90deg, rgba(13,148,136,0.18), rgba(13,148,136,0.05))",
      borderLeftColor: COLORS.teal,
      color: COLORS.sidebarActiveColor,
      fontWeight: 700,
      boxShadow: "inset 0 0 0 1px rgba(13,148,136,0.08)",
    },
    mainArea: { flex: 1, display: "flex", minHeight: 0, minWidth: 0, overflow: "visible" },
    content: { flex: 1, overflowY: "auto", overflowX: "hidden", minHeight: 0, minWidth: 0, padding: "12px 14px 16px" },
    rightPanel: {
      width: 260,
      background: COLORS.panelBg,
      borderLeft: `1px solid ${COLORS.border}`,
      overflowY: "auto",
      padding: 10,
      flexShrink: 0,
      backdropFilter: "blur(10px)",
      minHeight: 0,
    },
    card: {
      background: COLORS.white,
      borderRadius: 8,
      border: `1px solid ${COLORS.border}`,
      padding: 10,
      marginBottom: 8,
      boxShadow: "0 2px 10px rgba(15, 23, 42, 0.03)",
    },
    cardTitle: {
      fontSize: 13,
      fontWeight: 800,
      marginBottom: 6,
      color: COLORS.dark,
      letterSpacing: "-0.01em",
    },
    sectionTitle: { fontSize: 14, fontWeight: 800, marginBottom: 2, letterSpacing: "-0.02em", color: COLORS.dark },
    sectionSubtitle: { fontSize: 10, color: COLORS.gray, marginBottom: 8, lineHeight: 1.3 },
    formGroup: { marginBottom: 8 },
    fieldsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "0px 12px", alignItems: "start" },
    fieldSpanFull: { gridColumn: "1 / -1" },
    stackedFields: { display: "flex", flexDirection: "column", gap: 8 },
    label: { display: "block", fontSize: 8.5, fontWeight: 400, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 3, color: COLORS.label || COLORS.gray, lineHeight: 1.3 },
    input: {
      width: "100%",
      padding: "5px 7px",
      border: `1px solid ${COLORS.border}`,
      borderRadius: 5,
      fontSize: 11.5,
      lineHeight: 1.25,
      boxSizing: "border-box",
      background: COLORS.inputBg,
      color: COLORS.dark,
      transition: "border-color 0.2s ease, box-shadow 0.2s ease",
      boxShadow: "inset 0 1px 3px rgba(15, 23, 42, 0.03)",
    },
    textarea: {
      width: "100%",
      padding: "5px 7px",
      border: `1px solid ${COLORS.border}`,
      borderRadius: 5,
      fontSize: 11.5,
      lineHeight: 1.25,
      minHeight: 46,
      resize: "vertical",
      boxSizing: "border-box",
      background: COLORS.inputBg,
      color: COLORS.dark,
      boxShadow: "inset 0 1px 3px rgba(15, 23, 42, 0.03)",
    },
    select: {
      width: "100%",
      padding: "5px 7px",
      border: `1px solid ${COLORS.border}`,
      borderRadius: 5,
      fontSize: 11.5,
      lineHeight: 1.25,
      background: COLORS.inputBg,
      color: COLORS.dark,
      boxSizing: "border-box",
      boxShadow: "inset 0 1px 3px rgba(15, 23, 42, 0.03)",
    },
    radioGroup: { display: "flex", gap: 8, flexWrap: "wrap" },
    radioLabel: { display: "flex", alignItems: "center", gap: 4, fontSize: 11.5, cursor: "pointer", color: COLORS.dark },
    checkboxGroup: { display: "flex", flexDirection: "row", flexWrap: "wrap", gap: "3px 10px" },
    checkboxLabel: { display: "flex", alignItems: "center", gap: 5, fontSize: 11.5, cursor: "pointer", color: COLORS.dark },
    hopeTag: { display: "inline-block", padding: "2px 8px", borderRadius: 999, fontSize: 10, fontWeight: 800, background: COLORS.hopeTagBg, color: COLORS.hope, letterSpacing: "0.03em", textTransform: "uppercase" },
    sfvTag: { display: "inline-block", padding: "2px 8px", borderRadius: 999, fontSize: 10, fontWeight: 800, background: COLORS.sfvTagBg, color: COLORS.sfv, letterSpacing: "0.03em", textTransform: "uppercase" },
    cmsTag: { display: "inline-block", padding: "2px 8px", borderRadius: 999, fontSize: 10, fontWeight: 800, background: COLORS.cmsTagBg, color: COLORS.cms, letterSpacing: "0.03em", textTransform: "uppercase" },
    statusBadge: { display: "inline-flex", alignItems: "center", gap: 4, padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, letterSpacing: "0.04em", textTransform: "uppercase" },
    btnPrimary: { padding: "8px 14px", background: `linear-gradient(135deg, ${COLORS.teal} 0%, ${COLORS.tealDark} 100%)`, color: COLORS.textOnTeal, border: "none", borderRadius: 8, fontSize: 13, fontWeight: 700, cursor: "pointer", boxShadow: "0 8px 18px rgba(13, 148, 136, 0.2)" },
    btnSecondary: { padding: "8px 14px", background: COLORS.white, color: COLORS.dark, border: `1px solid ${COLORS.border}`, borderRadius: 8, fontSize: 13, fontWeight: 700, cursor: "pointer", boxShadow: "0 4px 12px rgba(15, 23, 42, 0.03)" },
    btnDanger: { padding: "8px 14px", background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)", color: "#FFFFFF", border: "none", borderRadius: 8, fontSize: 13, fontWeight: 700, cursor: "pointer", boxShadow: "0 8px 18px rgba(239, 68, 68, 0.2)" },
    // Fixed to the viewport (not sticky-in-flow) because `page` lets the
    // document itself scroll rather than an inner container — Save/Lock
    // must stay reachable no matter how far the RN has scrolled.
    footer: { position: "fixed", left: 0, right: 0, bottom: 0, zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "8px 16px", background: COLORS.panelBg, borderTop: `1px solid ${COLORS.border}`, boxShadow: "0 -4px 12px rgba(15, 23, 42, 0.08)" },
    footerSpacer: { height: 64 },
    table: { width: "100%", borderCollapse: "collapse", fontSize: 11.5 },
    th: { padding: "6px 10px", textAlign: "left", fontWeight: 700, fontSize: 10, textTransform: "uppercase", color: COLORS.gray, borderBottom: `2px solid ${COLORS.border}`, background: COLORS.bg },
    td: { padding: "6px 10px", borderBottom: `1px solid ${COLORS.border}` },
    infoBox: { padding: 10, background: COLORS.infoBoxBg, borderRadius: 8, border: `1px solid rgba(30,58,95,0.18)`, fontSize: 11.5, lineHeight: 1.4, marginBottom: 10, color: COLORS.dark },
    warningBox: { padding: 10, background: COLORS.warningBoxBg, borderRadius: 8, border: `1px solid rgba(245, 158, 11, 0.3)`, fontSize: 11.5, lineHeight: 1.4, marginBottom: 10, color: COLORS.dark },
    successBox: { padding: 10, background: COLORS.successBoxBg, borderRadius: 8, border: `1px solid rgba(16,185,129,0.26)`, fontSize: 11.5, lineHeight: 1.4, marginBottom: 10, color: COLORS.dark },
  };
}
