"""Regenerate sns-emr-frontend/src/components/rn-ica/structuredFindingRegistry.generated.js
from the backend's CONCEPT_REGISTRY (app/services/evidence/structured_findings.py),
which is the single source of truth.

Run this any time CONCEPT_REGISTRY changes so the frontend mirror never drifts.
Usage (from backend/):  python scripts/generate_frontend_concept_registry.py
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.services.evidence.structured_findings import CONCEPT_REGISTRY  # noqa: E402

FRONTEND_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "sns-emr-frontend", "src", "components", "rn-ica", "structuredFindingRegistry.generated.js",
)


def render_write(write) -> str:
    return (
        "{ path: %s, value: %s, op: %s, section: %s }"
        % (json.dumps(write.path), json.dumps(write.value), json.dumps(write.op), json.dumps(write.section))
    )


def render_concept(code: str, mapping) -> str:
    writes_src = ", ".join(render_write(w) for w in mapping.writes)
    slot_src = ""
    if mapping.value_slot is not None:
        slot = mapping.value_slot
        slot_src = (
            "    valueSlot: { kind: %s, path: %s, minValue: %s, maxValue: %s, maxLen: %s },\n"
            % (
                json.dumps(slot.kind),
                json.dumps(slot.path),
                json.dumps(slot.min_value),
                json.dumps(slot.max_value),
                json.dumps(slot.max_len),
            )
        )
    draft_src = ""
    return (
        "  %s: {\n    section: %s,\n    writes: [%s],\n%s%s  },"
        % (
            code,
            json.dumps(mapping.section),
            writes_src,
            draft_src,
            slot_src,
        )
    )


def main() -> None:
    lines = [
        "// AUTO-GENERATED MIRROR of backend app/services/evidence/structured_findings.py",
        "// CONCEPT_REGISTRY. Regenerate this file whenever the backend registry changes --",
        "// do NOT hand-edit concept entries here, they must stay byte-identical to the",
        "// server-controlled source of truth so a concept behaves identically whether it",
        "// was validated by the backend (note_draft_service.py / ai_extraction_service.py)",
        "// or applied here on the frontend.",
        "//",
        "// Generated by backend/scripts/generate_frontend_concept_registry.py -- do not",
        "// hand-edit. Re-run that script after any CONCEPT_REGISTRY change.",
        "export const CONCEPT_REGISTRY = {",
    ]
    for code, mapping in CONCEPT_REGISTRY.items():
        lines.append(render_concept(code, mapping))
    lines.append("};")
    content = "\n".join(lines) + "\n"
    with open(FRONTEND_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"Wrote {len(CONCEPT_REGISTRY)} concepts to {FRONTEND_PATH}")


if __name__ == "__main__":
    main()
