import api from './client';

export type VisitRecording = {
  id: string;
  client_recording_id: string | null;
  patient_id: string;
  visit_id: string | null;
  assessment_id: string | null;
  assessment_type: string | null;
  recorded_by: string;
  recorded_at: string;
  duration_seconds: number | null;
  size_bytes: number | null;
  mime_type: string | null;
  consent_confirmed: boolean;
  transcript_status: 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'RETRYING';
  transcript_provider: 'azure_speech' | 'manual_entry' | null;
  transcript_text: string | null;
  transcription_attempts: number;
  transcription_error: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  review_notes: string | null;
  ai_note_draft: {
    narrative: string;
    section_notes: Record<string, string>;
    detected_topics: string[];
    symptom_severity: Record<string, string>;
    structured_findings: Array<Record<string, unknown>>;
    generated_at: string;
    model: string;
  } | null;
};

export async function uploadVisitRecording(params: {
  patientId: string;
  audioBlob: Blob;
  consentConfirmed: boolean;
  visitId?: string | null;
  assessmentId?: string | null;
  assessmentType?: string | null;
  durationSeconds?: number | null;
  mimeType?: string;
  clientRecordingId?: string;
}): Promise<VisitRecording> {
  const form = new FormData();
  form.append('patient_id', params.patientId);
  form.append('consent_confirmed', String(params.consentConfirmed));
  if (params.visitId) form.append('visit_id', params.visitId);
  if (params.assessmentId) form.append('assessment_id', params.assessmentId);
  if (params.assessmentType) form.append('assessment_type', params.assessmentType);
  if (params.durationSeconds != null) form.append('duration_seconds', String(Math.round(params.durationSeconds)));
  // Idempotency key generated by the caller BEFORE the upload attempt, so a
  // retry (offline reconnect, flaky connection) can never create a
  // duplicate recording/transcription for the one visit that was recorded.
  if (params.clientRecordingId) form.append('client_recording_id', params.clientRecordingId);
  const ext = (params.mimeType || params.audioBlob.type || 'audio/webm').includes('webm') ? 'webm' : 'audio';
  form.append('audio', params.audioBlob, `recording.${ext}`);

  const response = await api.post<VisitRecording>('/visit-recordings', form, {
    headers: { 'Content-Type': 'multipart/form-data' },
  });
  return response.data;
}

export async function fetchPatientRecordings(patientId: string): Promise<{ recordings: VisitRecording[] }> {
  const response = await api.get<{ recordings: VisitRecording[] }>(`/visit-recordings/patient/${patientId}`);
  return response.data;
}

export function getRecordingAudioUrl(recordingId: string): string {
  const base = (api.defaults.baseURL || '').replace(/\/$/, '');
  return `${base}/visit-recordings/${recordingId}/audio`;
}

// The audio-stream endpoint requires the same Bearer auth as every other API
// call, which a plain <audio src="..."> can't send. Fetch it as an
// authenticated blob instead and hand the component an object URL to play.
export async function fetchRecordingAudioBlobUrl(recordingId: string): Promise<string> {
  const response = await api.get(`/visit-recordings/${recordingId}/audio`, { responseType: 'blob' });
  return URL.createObjectURL(response.data as Blob);
}

export async function markRecordingReviewed(recordingId: string, reviewNotes?: string): Promise<VisitRecording> {
  const response = await api.post<VisitRecording>(`/visit-recordings/${recordingId}/review`, {
    review_notes: reviewNotes || null,
  });
  return response.data;
}

// Manual transcript entry -- FAILED-state fallback ONLY. Automatic Azure
// Speech transcription is the normal path for every recording; the backend
// rejects this call unless transcript_status is already FAILED, so staff
// are never asked to type/paste a transcript that hasn't even been given
// a chance to auto-transcribe.
export async function saveRecordingTranscript(recordingId: string, transcriptText: string): Promise<VisitRecording> {
  const response = await api.put<VisitRecording>(`/visit-recordings/${recordingId}/transcript`, {
    transcript_text: transcriptText,
  });
  return response.data;
}

// Staff-initiated retry after automatic transcription attempts are
// exhausted (FAILED), e.g. once Azure Speech credentials are fixed.
// Idempotent -- safe to call repeatedly.
export async function retryRecordingTranscription(recordingId: string): Promise<VisitRecording> {
  const response = await api.post<VisitRecording>(`/visit-recordings/${recordingId}/retry-transcription`, {});
  return response.data;
}

export async function deleteVisitRecording(recordingId: string): Promise<void> {
  await api.delete(`/visit-recordings/${recordingId}`);
}
