# app/services/clinical_discipline_mapping.py

NOTE_CATEGORY_CLINICAL = "CLINICAL"
NOTE_CATEGORY_SPIRITUAL = "SPIRITUAL"
NOTE_CATEGORY_PSYCHOSOCIAL = "PSYCHOSOCIAL"


# ✅ WHO owns the note
DISCIPLINE_TO_PRIMARY_CATEGORY = {
    "RN": NOTE_CATEGORY_CLINICAL,
    "LVN": NOTE_CATEGORY_CLINICAL,
    "MD": NOTE_CATEGORY_CLINICAL,
    "CHHA": NOTE_CATEGORY_CLINICAL,

    "SC": NOTE_CATEGORY_SPIRITUAL,

    "SW": NOTE_CATEGORY_PSYCHOSOCIAL,
    "MSW": NOTE_CATEGORY_PSYCHOSOCIAL,
    "BSW": NOTE_CATEGORY_PSYCHOSOCIAL,
    "LCSW": NOTE_CATEGORY_PSYCHOSOCIAL,
}


def resolve_primary_note_category(discipline: str) -> str:
    return DISCIPLINE_TO_PRIMARY_CATEGORY.get(
        discipline,
        NOTE_CATEGORY_CLINICAL,
    )