export const COLORS = {
  bg: 'var(--sns-bg)',
  card: 'var(--sns-card)',
  cardSoft: 'var(--sns-cardSoft)',
  border: 'var(--sns-border)',
  teal: 'var(--sns-teal)',
  white: 'var(--sns-white)',
  muted: 'var(--sns-muted)',
  dim: 'var(--sns-dim)',
  green: 'var(--sns-green)',
  blue: 'var(--sns-blue)',
  purple: 'var(--sns-purple)',
  orange: 'var(--sns-orange)',
  red: 'var(--sns-red)',
  yellow: 'var(--sns-yellow)',
  pink: 'var(--sns-pink)',
  activeNav: 'rgba(16,183,162,0.12)',
};

export const S = {
  container: {
    display: 'flex',
    height: '100vh',
    background: COLORS.bg,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: COLORS.white,
  },
  sidebar: {
    width: 220,
    background: COLORS.card,
    borderRight: `1px solid ${COLORS.border}`,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 0 18px',
    flexShrink: 0,
    position: 'relative',
    boxShadow: 'inset -1px 0 0 rgba(148, 163, 184, 0.06)',
  },
  logo: {
    padding: '0 20px',
    marginBottom: 24,
  },
  logoText: {
    fontSize: 18,
    fontWeight: 800,
    color: COLORS.teal,
    margin: 0,
    lineHeight: 1.3,
    letterSpacing: '-0.02em',
  },
  logoSub: {
    fontSize: 10,
    fontWeight: 700,
    color: COLORS.dim,
    letterSpacing: 1,
    margin: '6px 0 0',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: '0 12px',
    flex: 1,
  },
  navItem: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 16px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: active ? 600 : 500,
    color: active ? COLORS.white : COLORS.muted,
    background: active ? COLORS.activeNav : 'transparent',
    borderLeft: active ? `3px solid ${COLORS.teal}` : '3px solid transparent',
    paddingLeft: active ? 13 : 16,
    width: '100%',
    textAlign: 'left',
    transition: 'all 0.15s ease',
    boxShadow: active ? 'inset 0 0 0 1px rgba(16,183,162,0.08)' : 'none',
  }),
  navIcon: {
    fontSize: 16,
    width: 20,
    textAlign: 'center',
  },
  userBadge: {
    position: 'absolute',
    bottom: 18,
    left: 16,
    right: 16,
    padding: '12px 16px',
    background: 'rgba(148, 163, 184, 0.08)',
    borderRadius: 10,
    border: `1px solid ${COLORS.border}`,
  },
  userName: {
    fontSize: 12,
    fontWeight: 600,
    color: COLORS.white,
    margin: 0,
  },
  userRole: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    color: COLORS.teal,
    margin: '4px 0 0',
  },
  main: {
    flex: 1,
    overflow: 'auto',
    padding: '26px 28px 32px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
    marginBottom: 20,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: COLORS.white,
    margin: 0,
    letterSpacing: '-0.02em',
  },
  pageSubtitle: {
    fontSize: 14,
    fontWeight: 400,
    color: COLORS.muted,
    margin: '6px 0 0',
    lineHeight: 1.5,
  },
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 16,
    marginBottom: 22,
  },
  statCard: {
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 12,
    padding: '18px 18px 16px',
    position: 'relative',
    boxShadow: '0 0 0 1px rgba(148, 163, 184, 0.03)',
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    margin: 0,
  },
  statValue: {
    fontSize: 30,
    fontWeight: 700,
    color: COLORS.white,
    margin: '8px 0 6px',
    lineHeight: 1.1,
    letterSpacing: '-0.03em',
  },
  statSub: (color) => ({
    fontSize: 11,
    fontWeight: 600,
    color: color || COLORS.teal,
  }),
  statDot: (color) => ({
    position: 'absolute',
    top: 16,
    right: 18,
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: color || COLORS.green,
    boxShadow: `0 0 0 4px ${color || COLORS.green}22`,
  }),
  card: {
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    boxShadow: '0 1px 0 rgba(15, 23, 42, 0.18)',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: COLORS.white,
    margin: '0 0 16px',
    letterSpacing: '-0.01em',
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: COLORS.dim,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    margin: 0,
  },
  tableHeader: {
    fontSize: 11,
    fontWeight: 700,
    color: COLORS.dim,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    padding: '8px 0',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  tableCell: {
    fontSize: 13,
    fontWeight: 400,
    color: COLORS.muted,
    padding: '12px 0',
    borderBottom: `1px solid ${COLORS.border}`,
    verticalAlign: 'middle',
  },
  tableCellBold: {
    fontSize: 14,
    fontWeight: 600,
    color: COLORS.white,
    padding: '12px 0',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  badge: (bg, color) => ({
    display: 'inline-block',
    padding: '3px 10px',
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
    color: color || '#fff',
    background: bg,
    letterSpacing: '0.01em',
  }),
  btn: (bg) => ({
    padding: '10px 18px',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 700,
    color: COLORS.white,
    background: bg || COLORS.teal,
    letterSpacing: '0.02em',
  }),
  btnOutline: {
    padding: '10px 18px',
    borderRadius: 8,
    border: `1px solid ${COLORS.border}`,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 700,
    color: COLORS.muted,
    background: 'transparent',
    letterSpacing: '0.02em',
  },
  searchBar: {
    flex: 1,
    background: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    padding: '10px 16px 10px 36px',
    fontSize: 13,
    color: COLORS.muted,
    outline: 'none',
  },
  select: {
    background: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    padding: '10px 12px',
    fontSize: 13,
    color: COLORS.white,
    outline: 'none',
  },
};
