"""Harden task model for hospice compliance

Revision ID: 3a88b97a921b
Revises: f6496a5dc397
Create Date: 2026-04-28 19:22:27.396589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a88b97a921b'
down_revision: Union[str, Sequence[str], None] = 'f6496a5dc397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
