"""add ontology disease blueprint tables

Revision ID: 718280baef7d
Revises: cd6205fb97e3
Create Date: 2026-09-01 10:16:35.780735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '718280baef7d'
down_revision: Union[str, Sequence[str], None] = 'cd6205fb97e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_body_system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('length(trim(system_name)) > 0', name=op.f('ck_ontology_body_system_ck_ontology_body_system_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_body_system'))
    )
    op.create_index(op.f('ix_ontology_body_system_system_name'), 'ontology_body_system', ['system_name'], unique=True)
    op.create_table('ontology_evidence_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_type', sa.String(length=64), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('evidence_source', sa.String(length=255), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('review_trigger', sa.String(length=128), nullable=True),
    sa.Column('patient_fact_requires_evidence', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_evidence_rule')),
    sa.UniqueConstraint('concept_type', 'concept_id', name='uq_ontology_evidence_rule_concept')
    )
    op.create_index(op.f('ix_ontology_evidence_rule_concept_id'), 'ontology_evidence_rule', ['concept_id'], unique=False)
    op.create_index(op.f('ix_ontology_evidence_rule_concept_type'), 'ontology_evidence_rule', ['concept_type'], unique=False)
    op.create_table('ontology_relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_concept_type', sa.String(length=64), nullable=False),
    sa.Column('source_concept_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('target_concept_type', sa.String(length=64), nullable=False),
    sa.Column('target_concept_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_relationship')),
    sa.UniqueConstraint('source_concept_type', 'source_concept_id', 'relationship_type', 'target_concept_type', 'target_concept_id', name='uq_ontology_relationship_edge')
    )
    op.create_index(op.f('ix_ontology_relationship_relationship_type'), 'ontology_relationship', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_ontology_relationship_source_concept_id'), 'ontology_relationship', ['source_concept_id'], unique=False)
    op.create_index(op.f('ix_ontology_relationship_source_concept_type'), 'ontology_relationship', ['source_concept_type'], unique=False)
    op.create_index(op.f('ix_ontology_relationship_target_concept_id'), 'ontology_relationship', ['target_concept_id'], unique=False)
    op.create_index(op.f('ix_ontology_relationship_target_concept_type'), 'ontology_relationship', ['target_concept_type'], unique=False)
    op.create_table('ontology_disease_family',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body_system_id', sa.UUID(), nullable=False),
    sa.Column('family_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('length(trim(family_name)) > 0', name=op.f('ck_ontology_disease_family_ck_ontology_disease_family_n_ac5a')),
    sa.ForeignKeyConstraint(['body_system_id'], ['ontology_body_system.id'], name=op.f('fk_ontology_disease_family_body_system_id_ontology_body_system'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_family')),
    sa.UniqueConstraint('body_system_id', 'family_name', name='uq_ontology_disease_family_system_name')
    )
    op.create_index(op.f('ix_ontology_disease_family_body_system_id'), 'ontology_disease_family', ['body_system_id'], unique=False)
    op.create_index(op.f('ix_ontology_disease_family_family_name'), 'ontology_disease_family', ['family_name'], unique=False)
    op.create_table('ontology_disease',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_family_id', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.Column('disease_category', sa.String(length=64), nullable=True),
    sa.Column('primary_organ', sa.String(length=128), nullable=True),
    sa.Column('disease_type', sa.String(length=128), nullable=True),
    sa.Column('disease_description', sa.Text(), nullable=True),
    sa.Column('clinical_purpose', sa.Text(), nullable=True),
    sa.Column('hospice_relevance', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('length(trim(disease_name)) > 0', name=op.f('ck_ontology_disease_ck_ontology_disease_name_not_blank')),
    sa.ForeignKeyConstraint(['disease_family_id'], ['ontology_disease_family.id'], name=op.f('fk_ontology_disease_disease_family_id_ontology_disease_family'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease'))
    )
    op.create_index(op.f('ix_ontology_disease_disease_category'), 'ontology_disease', ['disease_category'], unique=False)
    op.create_index(op.f('ix_ontology_disease_disease_family_id'), 'ontology_disease', ['disease_family_id'], unique=False)
    op.create_index(op.f('ix_ontology_disease_disease_name'), 'ontology_disease', ['disease_name'], unique=True)
    op.create_table('ontology_disease_complication',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('complication_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('common_occurrence', sa.String(length=64), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_complication_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_complication')),
    sa.UniqueConstraint('disease_id', 'complication_name', name='uq_ontology_disease_complication_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_complication_disease_id'), 'ontology_disease_complication', ['disease_id'], unique=False)
    op.create_table('ontology_disease_diagnostic_test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('expected_findings', sa.Text(), nullable=True),
    sa.Column('evidence_weight', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_diagnostic_test_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_diagnostic_test')),
    sa.UniqueConstraint('disease_id', 'test_name', name='uq_ontology_disease_diagnostic_test_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_diagnostic_test_disease_id'), 'ontology_disease_diagnostic_test', ['disease_id'], unique=False)
    op.create_table('ontology_disease_finding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('finding_name', sa.String(length=255), nullable=False),
    sa.Column('finding_description', sa.Text(), nullable=True),
    sa.Column('severity_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_evidence_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_finding_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_finding')),
    sa.UniqueConstraint('disease_id', 'finding_name', name='uq_ontology_disease_finding_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_finding_disease_id'), 'ontology_disease_finding', ['disease_id'], unique=False)
    op.create_table('ontology_disease_functional_impact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('impact_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_functional_impact_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_functional_impact')),
    sa.UniqueConstraint('disease_id', 'impact_name', name='uq_ontology_disease_functional_impact_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_functional_impact_disease_id'), 'ontology_disease_functional_impact', ['disease_id'], unique=False)
    op.create_table('ontology_disease_hospice_eligibility_support',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('lcd_reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_hospice_eligibility_support_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_hospice_eligibility_support')),
    sa.UniqueConstraint('disease_id', 'indicator_name', name='uq_ontology_disease_hospice_eligibility_support_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_hospice_eligibility_support_disease_id'), 'ontology_disease_hospice_eligibility_support', ['disease_id'], unique=False)
    op.create_table('ontology_disease_interdisciplinary_trigger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('discipline', sa.String(length=64), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.CheckConstraint("discipline IN ('RN', 'PHYSICIAN', 'MSW', 'BSW', 'CHAPLAIN', 'VOLUNTEER', 'BEREAVEMENT', 'DIETICIAN', 'PT', 'OT', 'IDG')", name=op.f('ck_ontology_disease_interdisciplinary_trigger_ck_ontolo_c4a3')),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_interdisciplinary_trigger_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_interdisciplinary_trigger'))
    )
    op.create_index(op.f('ix_ontology_disease_interdisciplinary_trigger_disease_id'), 'ontology_disease_interdisciplinary_trigger', ['disease_id'], unique=False)
    op.create_table('ontology_disease_lab',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('lab_name', sa.String(length=255), nullable=False),
    sa.Column('normal_range', sa.String(length=255), nullable=True),
    sa.Column('expected_abnormal_range', sa.String(length=255), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('hospice_significance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_lab_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_lab')),
    sa.UniqueConstraint('disease_id', 'lab_name', name='uq_ontology_disease_lab_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_lab_disease_id'), 'ontology_disease_lab', ['disease_id'], unique=False)
    op.create_table('ontology_disease_medication',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('drug_class', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('expected_benefits', sa.Text(), nullable=True),
    sa.Column('common_side_effects', sa.Text(), nullable=True),
    sa.Column('hospice_relevance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_medication_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_medication')),
    sa.UniqueConstraint('disease_id', 'medication_name', name='uq_ontology_disease_medication_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_medication_disease_id'), 'ontology_disease_medication', ['disease_id'], unique=False)
    op.create_table('ontology_disease_nutritional_impact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('impact_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_nutritional_impact_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_nutritional_impact')),
    sa.UniqueConstraint('disease_id', 'impact_name', name='uq_ontology_disease_nutritional_impact_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_nutritional_impact_disease_id'), 'ontology_disease_nutritional_impact', ['disease_id'], unique=False)
    op.create_table('ontology_disease_prognostic_indicator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_prognostic_indicator_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_prognostic_indicator')),
    sa.UniqueConstraint('disease_id', 'indicator_name', name='uq_ontology_disease_prognostic_indicator_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_prognostic_indicator_disease_id'), 'ontology_disease_prognostic_indicator', ['disease_id'], unique=False)
    op.create_table('ontology_disease_psychosocial_concern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('concern_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_psychosocial_concern_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_psychosocial_concern')),
    sa.UniqueConstraint('disease_id', 'concern_name', name='uq_ontology_disease_psychosocial_concern_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_psychosocial_concern_disease_id'), 'ontology_disease_psychosocial_concern', ['disease_id'], unique=False)
    op.create_table('ontology_disease_spiritual_concern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('concern_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_spiritual_concern_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_spiritual_concern')),
    sa.UniqueConstraint('disease_id', 'concern_name', name='uq_ontology_disease_spiritual_concern_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_spiritual_concern_disease_id'), 'ontology_disease_spiritual_concern', ['disease_id'], unique=False)
    op.create_table('ontology_disease_symptom',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('symptom_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hospice_relevance', sa.Text(), nullable=True),
    sa.Column('severity_scale', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_symptom_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_symptom')),
    sa.UniqueConstraint('disease_id', 'symptom_name', name='uq_ontology_disease_symptom_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_symptom_disease_id'), 'ontology_disease_symptom', ['disease_id'], unique=False)
    op.create_table('ontology_disease_treatment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('treatment_name', sa.String(length=255), nullable=False),
    sa.Column('treatment_category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint("treatment_category IN ('DISEASE_DIRECTED', 'SUPPORTIVE', 'HOSPICE')", name=op.f('ck_ontology_disease_treatment_ck_ontology_disease_treat_1b8a')),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_treatment_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_treatment')),
    sa.UniqueConstraint('disease_id', 'treatment_name', 'treatment_category', name='uq_ontology_disease_treatment_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_treatment_disease_id'), 'ontology_disease_treatment', ['disease_id'], unique=False)
    # ### end Alembic commands (unrelated pre-existing schema drift excluded --
    # this migration is scoped only to the ontology disease blueprint tables) ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontology_disease_treatment_disease_id'), table_name='ontology_disease_treatment')
    op.drop_table('ontology_disease_treatment')
    op.drop_index(op.f('ix_ontology_disease_symptom_disease_id'), table_name='ontology_disease_symptom')
    op.drop_table('ontology_disease_symptom')
    op.drop_index(op.f('ix_ontology_disease_spiritual_concern_disease_id'), table_name='ontology_disease_spiritual_concern')
    op.drop_table('ontology_disease_spiritual_concern')
    op.drop_index(op.f('ix_ontology_disease_psychosocial_concern_disease_id'), table_name='ontology_disease_psychosocial_concern')
    op.drop_table('ontology_disease_psychosocial_concern')
    op.drop_index(op.f('ix_ontology_disease_prognostic_indicator_disease_id'), table_name='ontology_disease_prognostic_indicator')
    op.drop_table('ontology_disease_prognostic_indicator')
    op.drop_index(op.f('ix_ontology_disease_nutritional_impact_disease_id'), table_name='ontology_disease_nutritional_impact')
    op.drop_table('ontology_disease_nutritional_impact')
    op.drop_index(op.f('ix_ontology_disease_medication_disease_id'), table_name='ontology_disease_medication')
    op.drop_table('ontology_disease_medication')
    op.drop_index(op.f('ix_ontology_disease_lab_disease_id'), table_name='ontology_disease_lab')
    op.drop_table('ontology_disease_lab')
    op.drop_index(op.f('ix_ontology_disease_interdisciplinary_trigger_disease_id'), table_name='ontology_disease_interdisciplinary_trigger')
    op.drop_table('ontology_disease_interdisciplinary_trigger')
    op.drop_index(op.f('ix_ontology_disease_hospice_eligibility_support_disease_id'), table_name='ontology_disease_hospice_eligibility_support')
    op.drop_table('ontology_disease_hospice_eligibility_support')
    op.drop_index(op.f('ix_ontology_disease_functional_impact_disease_id'), table_name='ontology_disease_functional_impact')
    op.drop_table('ontology_disease_functional_impact')
    op.drop_index(op.f('ix_ontology_disease_finding_disease_id'), table_name='ontology_disease_finding')
    op.drop_table('ontology_disease_finding')
    op.drop_index(op.f('ix_ontology_disease_diagnostic_test_disease_id'), table_name='ontology_disease_diagnostic_test')
    op.drop_table('ontology_disease_diagnostic_test')
    op.drop_index(op.f('ix_ontology_disease_complication_disease_id'), table_name='ontology_disease_complication')
    op.drop_table('ontology_disease_complication')
    op.drop_index(op.f('ix_ontology_disease_disease_name'), table_name='ontology_disease')
    op.drop_index(op.f('ix_ontology_disease_disease_family_id'), table_name='ontology_disease')
    op.drop_index(op.f('ix_ontology_disease_disease_category'), table_name='ontology_disease')
    op.drop_table('ontology_disease')
    op.drop_index(op.f('ix_ontology_disease_family_family_name'), table_name='ontology_disease_family')
    op.drop_index(op.f('ix_ontology_disease_family_body_system_id'), table_name='ontology_disease_family')
    op.drop_table('ontology_disease_family')
    op.drop_index(op.f('ix_ontology_relationship_target_concept_type'), table_name='ontology_relationship')
    op.drop_index(op.f('ix_ontology_relationship_target_concept_id'), table_name='ontology_relationship')
    op.drop_index(op.f('ix_ontology_relationship_source_concept_type'), table_name='ontology_relationship')
    op.drop_index(op.f('ix_ontology_relationship_source_concept_id'), table_name='ontology_relationship')
    op.drop_index(op.f('ix_ontology_relationship_relationship_type'), table_name='ontology_relationship')
    op.drop_table('ontology_relationship')
    op.drop_index(op.f('ix_ontology_evidence_rule_concept_type'), table_name='ontology_evidence_rule')
    op.drop_index(op.f('ix_ontology_evidence_rule_concept_id'), table_name='ontology_evidence_rule')
    op.drop_table('ontology_evidence_rule')
    op.drop_index(op.f('ix_ontology_body_system_system_name'), table_name='ontology_body_system')
    op.drop_table('ontology_body_system')
    # ### end Alembic commands ###
