"""add ontology tier4 variant and tier5 applicability tables

Revision ID: af1833134391
Revises: d635c5937cb5
Create Date: 2026-09-01 16:33:31.575950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1833134391'
down_revision: Union[str, Sequence[str], None] = 'd635c5937cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_disease_variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('parent_variant_id', sa.UUID(), nullable=True),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('variant_dimension', sa.String(length=32), nullable=False),
    sa.Column('variant_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('hospice_relevance', sa.Text(), nullable=True),
    sa.Column('evidence_requirement', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("variant_dimension IN ('MECHANISM', 'PATHOLOGICAL_SUBTYPE', 'HISTOLOGY', 'MOLECULAR_SUBTYPE', 'ANATOMICAL_LOCATION', 'PRIMARY_SITE', 'VASCULAR_TERRITORY', 'HEMISPHERE', 'DOMINANCE', 'LATERALITY', 'CORTICAL_LOCATION', 'SUBCORTICAL_LOCATION', 'DEEP_STRUCTURE', 'BRAINSTEM_LEVEL', 'CEREBELLAR_LOCATION', 'CARDIAC_SIDE', 'CARDIAC_CHAMBER', 'PHYSIOLOGICAL_PHENOTYPE', 'SEVERITY_CLASS', 'STAGE', 'GRADE', 'DISEASE_PHASE', 'RECURRENCE_STATE', 'METASTATIC_STATE', 'METASTATIC_DESTINATION', 'TREATMENT_STATE', 'RESIDUAL_DEFICIT_STATE')", name=op.f('ck_ontology_disease_variant_ck_ontology_disease_variant_b8b3')),
    sa.CheckConstraint('length(trim(variant_name)) > 0', name=op.f('ck_ontology_disease_variant_ck_ontology_disease_variant_48e2')),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_variant_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_variant_id'], ['ontology_disease_variant.id'], name=op.f('fk_ontology_disease_variant_parent_variant_id_ontology_disease_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_variant')),
    sa.UniqueConstraint('disease_id', 'variant_dimension', 'normalized_name', name='uq_ontology_disease_variant_disease_dimension_name')
    )
    op.create_index(op.f('ix_ontology_disease_variant_active'), 'ontology_disease_variant', ['active'], unique=False)
    op.create_index(op.f('ix_ontology_disease_variant_disease_id'), 'ontology_disease_variant', ['disease_id'], unique=False)
    op.create_index(op.f('ix_ontology_disease_variant_normalized_name'), 'ontology_disease_variant', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_ontology_disease_variant_parent_variant_id'), 'ontology_disease_variant', ['parent_variant_id'], unique=False)
    op.create_index(op.f('ix_ontology_disease_variant_variant_dimension'), 'ontology_disease_variant', ['variant_dimension'], unique=False)
    op.create_table('ontology_concept_variant_applicability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('concept_type', sa.String(length=64), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('applicability_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_requirement', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("applicability_type IN ('APPLIES_TO', 'EXPECTED_WITH', 'STRONGLY_ASSOCIATED_WITH', 'MAY_OCCUR_WITH', 'SUPPORTS_DIFFERENTIATION', 'CONTRAINDICATED_FOR', 'TREATMENT_SPECIFIC_TO', 'PROGNOSTIC_FOR', 'END_STAGE_SUPPORT_FOR', 'HOSPICE_SUPPORT_FOR')", name=op.f('ck_ontology_concept_variant_applicability_ck_ontology_c_13ba')),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_concept_variant_applicability_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['ontology_disease_variant.id'], name=op.f('fk_ontology_concept_variant_applicability_variant_id_ontology_disease_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_concept_variant_applicability')),
    sa.UniqueConstraint('concept_type', 'concept_id', 'variant_id', 'applicability_type', name='uq_ontology_concept_variant_applicability_edge')
    )
    op.create_index(op.f('ix_ontology_concept_variant_applicability_active'), 'ontology_concept_variant_applicability', ['active'], unique=False)
    op.create_index(op.f('ix_ontology_concept_variant_applicability_applicability_type'), 'ontology_concept_variant_applicability', ['applicability_type'], unique=False)
    op.create_index(op.f('ix_ontology_concept_variant_applicability_concept_id'), 'ontology_concept_variant_applicability', ['concept_id'], unique=False)
    op.create_index(op.f('ix_ontology_concept_variant_applicability_concept_type'), 'ontology_concept_variant_applicability', ['concept_type'], unique=False)
    op.create_index(op.f('ix_ontology_concept_variant_applicability_disease_id'), 'ontology_concept_variant_applicability', ['disease_id'], unique=False)
    op.create_index(op.f('ix_ontology_concept_variant_applicability_variant_id'), 'ontology_concept_variant_applicability', ['variant_id'], unique=False)
    # ### end Alembic commands - unrelated pre-existing schema drift excluded --
    # this migration is scoped only to the ontology_disease_variant and
    # ontology_concept_variant_applicability tables ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontology_concept_variant_applicability_variant_id'), table_name='ontology_concept_variant_applicability')
    op.drop_index(op.f('ix_ontology_concept_variant_applicability_disease_id'), table_name='ontology_concept_variant_applicability')
    op.drop_index(op.f('ix_ontology_concept_variant_applicability_concept_type'), table_name='ontology_concept_variant_applicability')
    op.drop_index(op.f('ix_ontology_concept_variant_applicability_concept_id'), table_name='ontology_concept_variant_applicability')
    op.drop_index(op.f('ix_ontology_concept_variant_applicability_applicability_type'), table_name='ontology_concept_variant_applicability')
    op.drop_index(op.f('ix_ontology_concept_variant_applicability_active'), table_name='ontology_concept_variant_applicability')
    op.drop_table('ontology_concept_variant_applicability')
    op.drop_index(op.f('ix_ontology_disease_variant_variant_dimension'), table_name='ontology_disease_variant')
    op.drop_index(op.f('ix_ontology_disease_variant_parent_variant_id'), table_name='ontology_disease_variant')
    op.drop_index(op.f('ix_ontology_disease_variant_normalized_name'), table_name='ontology_disease_variant')
    op.drop_index(op.f('ix_ontology_disease_variant_disease_id'), table_name='ontology_disease_variant')
    op.drop_index(op.f('ix_ontology_disease_variant_active'), table_name='ontology_disease_variant')
    op.drop_table('ontology_disease_variant')
    # ### end Alembic commands ###
