"""add ontology A-K domain E H K tables

Revision ID: d635c5937cb5
Revises: 718280baef7d
Create Date: 2026-09-01 11:13:55.212026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd635c5937cb5'
down_revision: Union[str, Sequence[str], None] = '718280baef7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_disease_end_stage_finding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('finding_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_requirement', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('hospice_relevance', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_end_stage_finding_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_end_stage_finding')),
    sa.UniqueConstraint('disease_id', 'finding_name', name='uq_ontology_disease_end_stage_finding_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_end_stage_finding_disease_id'), 'ontology_disease_end_stage_finding', ['disease_id'], unique=False)
    op.create_table('ontology_disease_treatment_limitation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('limitation_name', sa.String(length=255), nullable=False),
    sa.Column('limitation_category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_requirement', sa.Text(), nullable=True),
    sa.Column('hospice_relevance', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("limitation_category IN ('OPTIMALLY_TREATED', 'TREATMENT_FAILED', 'TREATMENT_INTOLERANT', 'NOT_A_CANDIDATE', 'TREATMENT_DECLINED', 'TREATMENT_DISCONTINUED', 'TREATMENT_CONTRAINDICATED', 'COMFORT_FOCUSED')", name=op.f('ck_ontology_disease_treatment_limitation_ck_ontology_di_c509')),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_treatment_limitation_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_treatment_limitation')),
    sa.UniqueConstraint('disease_id', 'limitation_name', 'limitation_category', name='uq_ontology_disease_treatment_limitation_disease_name')
    )
    op.create_index(op.f('ix_ontology_disease_treatment_limitation_disease_id'), 'ontology_disease_treatment_limitation', ['disease_id'], unique=False)
    op.create_table('ontology_disease_validation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('validation_type', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validator_version', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("validation_status IN ('PASS', 'FAIL', 'WARNING')", name=op.f('ck_ontology_disease_validation_result_ck_ontology_disea_70a7')),
    sa.CheckConstraint("validation_type IN ('DUPLICATE', 'ORPHAN', 'HIERARCHY', 'DOMAIN_COMPLETENESS', 'EVIDENCE_COVERAGE', 'RELATIONSHIP_INTEGRITY', 'SOURCE_PROVENANCE')", name=op.f('ck_ontology_disease_validation_result_ck_ontology_disea_43e0')),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology_disease.id'], name=op.f('fk_ontology_disease_validation_result_disease_id_ontology_disease'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_disease_validation_result'))
    )
    op.create_index(op.f('ix_ontology_disease_validation_result_disease_id'), 'ontology_disease_validation_result', ['disease_id'], unique=False)
    # ### end Alembic commands - unrelated pre-existing schema drift excluded --
    # this migration is scoped only to the ontology A-K domain E/H/K tables ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontology_disease_validation_result_disease_id'), table_name='ontology_disease_validation_result')
    op.drop_table('ontology_disease_validation_result')
    op.drop_index(op.f('ix_ontology_disease_treatment_limitation_disease_id'), table_name='ontology_disease_treatment_limitation')
    op.drop_table('ontology_disease_treatment_limitation')
    op.drop_index(op.f('ix_ontology_disease_end_stage_finding_disease_id'), table_name='ontology_disease_end_stage_finding')
    op.drop_table('ontology_disease_end_stage_finding')
    # ### end Alembic commands ###
