"""Add IDG review tracking

Revision ID: e5a80a8efc1d
Revises: 94a9761b97fa
Create Date: 2026-04-28 08:57:48.624539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a80a8efc1d'
down_revision: Union[str, Sequence[str], None] = '94a9761b97fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idg_reviews',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('rn_present', sa.Boolean(), nullable=True),
    sa.Column('physician_present', sa.Boolean(), nullable=True),
    sa.Column('social_worker_present', sa.Boolean(), nullable=True),
    sa.Column('chaplain_present', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idg_reviews')
    # ### end Alembic commands ###
