"""create benefit periods table

Revision ID: eb851de9e5e1
Revises: 924041973331
Create Date: 2026-04-30 12:40:19.663958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb851de9e5e1'
down_revision: Union[str, Sequence[str], None] = '924041973331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_periods',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_periods_created_by'), 'benefit_periods', ['created_by'], unique=False)
    op.create_index(op.f('ix_benefit_periods_end_date'), 'benefit_periods', ['end_date'], unique=False)
    op.create_index(op.f('ix_benefit_periods_patient_id'), 'benefit_periods', ['patient_id'], unique=False)
    op.create_index(op.f('ix_benefit_periods_start_date'), 'benefit_periods', ['start_date'], unique=False)
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_type', postgresql.ENUM('HUV', 'SFV', 'OTHER', name='tasks_task_type_enum'), autoincrement=False, nullable=True),
    sa.Column('discipline', postgresql.ENUM('RN', 'MD', 'NP', 'SW', 'CHAPLAIN', 'AIDE', name='tasks_discipline_enum'), autoincrement=False, nullable=True),
    sa.Column('origin', postgresql.ENUM('ADMISSION', 'PERIODIC', 'MANUAL', name='tasks_origin_enum'), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('benefit_period_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('regulatory_basis', postgresql.ENUM('IDG', 'VISIT_FREQUENCY', 'F2F', 'CERTIFICATION', 'ADMISSION_REQUIREMENT', name='tasks_regulatory_basis_enum'), autoincrement=False, nullable=True),
    sa.Column('completion_reference_type', postgresql.ENUM('VISIT', 'NOTE', 'ORDER', name='tasks_completion_ref_enum'), autoincrement=False, nullable=True),
    sa.Column('completion_reference_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('tasks_assigned_user_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('tasks_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.drop_index(op.f('ix_benefit_periods_start_date'), table_name='benefit_periods')
    op.drop_index(op.f('ix_benefit_periods_patient_id'), table_name='benefit_periods')
    op.drop_index(op.f('ix_benefit_periods_end_date'), table_name='benefit_periods')
    op.drop_index(op.f('ix_benefit_periods_created_by'), table_name='benefit_periods')
    op.drop_table('benefit_periods')
    # ### end Alembic commands ###
