"""add patient evidence harvester tables

Revision ID: ec6af346493d
Revises: 5d3e2a1b4c6d
Create Date: 2026-08-25 11:29:01.895594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec6af346493d'
down_revision: Union[str, Sequence[str], None] = '5d3e2a1b4c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_evidence_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('communication_log_id', sa.UUID(), nullable=True),
    sa.Column('discipline', sa.String(length=16), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by_name', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_documentation', sa.Text(), nullable=False),
    sa.Column('harvested_by', sa.String(length=64), server_default=sa.text("'ai_evidence_harvester'"), nullable=False),
    sa.Column('harvested_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('ai_extraction_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ai_extraction_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_evidence_records_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_patient_evidence_records_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_patient_evidence_records_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_evidence_records'))
    )
    op.create_index('ix_evidence_records_patient_source', 'patient_evidence_records', ['patient_id', 'source_type'], unique=False)
    op.create_index('ix_evidence_records_tenant_recorded_at', 'patient_evidence_records', ['tenant_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_communication_log_id'), 'patient_evidence_records', ['communication_log_id'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_discipline'), 'patient_evidence_records', ['discipline'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_patient_id'), 'patient_evidence_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_source_record_id'), 'patient_evidence_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_source_type'), 'patient_evidence_records', ['source_type'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_tenant_id'), 'patient_evidence_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_patient_evidence_records_visit_id'), 'patient_evidence_records', ['visit_id'], unique=False)
    op.create_table('patient_harvested_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('evidence_record_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_discipline', sa.String(length=16), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_key', sa.String(length=128), nullable=False),
    sa.Column('signal_text', sa.Text(), nullable=False),
    sa.Column('original_text_excerpt', sa.Text(), nullable=False),
    sa.Column('comparison_text', sa.Text(), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('clinical_system', sa.String(length=64), nullable=True),
    sa.Column('requires_rn_review', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('requires_idg_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_poc_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('review_status', sa.String(length=24), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_disposition_reason', sa.Text(), nullable=True),
    sa.Column('linked_problem_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['patient_evidence_records.id'], name=op.f('fk_patient_harvested_signals_evidence_record_id_patient_evidence_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_harvested_signals_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_patient_harvested_signals_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_harvested_signals'))
    )
    op.create_index('ix_harvested_signals_patient_status', 'patient_harvested_signals', ['patient_id', 'review_status'], unique=False)
    op.create_index('ix_harvested_signals_tenant_recorded_at', 'patient_harvested_signals', ['tenant_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_evidence_record_id'), 'patient_harvested_signals', ['evidence_record_id'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_linked_problem_id'), 'patient_harvested_signals', ['linked_problem_id'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_patient_id'), 'patient_harvested_signals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_review_status'), 'patient_harvested_signals', ['review_status'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_signal_key'), 'patient_harvested_signals', ['signal_key'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_source_discipline'), 'patient_harvested_signals', ['source_discipline'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_source_type'), 'patient_harvested_signals', ['source_type'], unique=False)
    op.create_index(op.f('ix_patient_harvested_signals_tenant_id'), 'patient_harvested_signals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_harvested_signals_tenant_id'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_source_type'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_source_discipline'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_signal_key'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_review_status'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_patient_id'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_linked_problem_id'), table_name='patient_harvested_signals')
    op.drop_index(op.f('ix_patient_harvested_signals_evidence_record_id'), table_name='patient_harvested_signals')
    op.drop_index('ix_harvested_signals_tenant_recorded_at', table_name='patient_harvested_signals')
    op.drop_index('ix_harvested_signals_patient_status', table_name='patient_harvested_signals')
    op.drop_table('patient_harvested_signals')
    op.drop_index(op.f('ix_patient_evidence_records_visit_id'), table_name='patient_evidence_records')
    op.drop_index(op.f('ix_patient_evidence_records_tenant_id'), table_name='patient_evidence_records')
    op.drop_index(op.f('ix_patient_evidence_records_source_type'), table_name='patient_evidence_records')
    op.drop_index(op.f('ix_patient_evidence_records_source_record_id'), table_name='patient_evidence_records')
    op.drop_index(op.f('ix_patient_evidence_records_patient_id'), table_name='patient_evidence_records')
    op.drop_index(op.f('ix_patient_evidence_records_discipline'), table_name='patient_evidence_records')
    op.drop_index(op.f('ix_patient_evidence_records_communication_log_id'), table_name='patient_evidence_records')
    op.drop_index('ix_evidence_records_tenant_recorded_at', table_name='patient_evidence_records')
    op.drop_index('ix_evidence_records_patient_source', table_name='patient_evidence_records')
    op.drop_table('patient_evidence_records')
    # ### end Alembic commands ###
