"""Add IDG meetings

Revision ID: efb85249ff6a
Revises: e5a80a8efc1d
Create Date: 2026-04-28 09:25:33.958712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb85249ff6a'
down_revision: Union[str, Sequence[str], None] = 'e5a80a8efc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idg_meetings',
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('rn_required', sa.Boolean(), nullable=True),
    sa.Column('physician_required', sa.Boolean(), nullable=True),
    sa.Column('social_worker_required', sa.Boolean(), nullable=True),
    sa.Column('chaplain_required', sa.Boolean(), nullable=True),
    sa.Column('rn_present', sa.Boolean(), nullable=True),
    sa.Column('physician_present', sa.Boolean(), nullable=True),
    sa.Column('social_worker_present', sa.Boolean(), nullable=True),
    sa.Column('chaplain_present', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idg_meetings')
    # ### end Alembic commands ###
