from enum import StrEnum


class IDGImpactLevel(StrEnum):
    ADMINISTRATIVE = "ADMINISTRATIVE"
    CLINICAL = "CLINICAL"
    SIGNIFICANT = "SIGNIFICANT"
    IDG_REQUIRED = "IDG_REQUIRED"


class IDGActivationRoute(StrEnum):
    ADMIN_ONLY = "ADMIN_ONLY"
    CLINICIAN_REVIEW = "CLINICIAN_REVIEW"
    MSW_REVIEW = "MSW_REVIEW"
    IDG_REVIEW_ONLY = "IDG_REVIEW_ONLY"

    CLINICIAN_MD_REPORT = "CLINICIAN_MD_REPORT"

    CLINICIAN_ADMIN_MD_REPORT = (
        "CLINICIAN_ADMIN_MD_REPORT"
    )

    CLINICIAN_MSW_SC_AS_NEEDED = (
        "CLINICIAN_MSW_SC_AS_NEEDED"
    )

    ADMIN_CLINICIAN_REPORT = (
        "ADMIN_CLINICIAN_REPORT"
    )

    CLINICIAN_OR_MSW_REVIEW = (
        "CLINICIAN_OR_MSW_REVIEW"
    )