export const COLORS = {
  bg: 'var(--sns-bg)',
  card: 'var(--sns-card)',
  border: 'var(--sns-border)',
  teal: 'var(--sns-teal)',
  white: 'var(--sns-white)',
  offWhite: 'var(--sns-bgAlt)',
  textPrimary: 'var(--sns-white)',
  muted: 'var(--sns-muted)',
  dim: 'var(--sns-dim)',
  green: 'var(--sns-green)',
  red: 'var(--sns-red)',
  orange: 'var(--sns-orange)',
  blue: 'var(--sns-blue)',
  purple: 'var(--sns-purple)',
  pink: 'var(--sns-pink)',
  yellow: 'var(--sns-yellow)',

  primary: 'var(--sns-teal)',
  secondary: 'var(--sns-blue)',
  success: 'var(--sns-green)',
  warning: 'var(--sns-orange)',
  danger: 'var(--sns-red)',
  text: 'var(--sns-white)',
  textDim: 'var(--sns-muted)',
  info: 'var(--sns-blue)',
};

export const S = {
  pageTitle: { fontSize: 22, fontWeight: 700, color: COLORS.white, margin: 0 },
  pageSubtitle: { fontSize: 13, fontWeight: 400, color: COLORS.muted, margin: '4px 0 0' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 },
  statsRow: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 16, marginBottom: 24 },
  statCard: { background: COLORS.card, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: '20px 18px', position: 'relative' },
  statValue: { fontSize: 28, fontWeight: 700, color: COLORS.white, margin: '6px 0 4px' },
  statDot: (color) => ({ width: 8, height: 8, borderRadius: '50%', background: color, position: 'absolute', top: 14, right: 14 }),
  statSub: (color) => ({ fontSize: 11, fontWeight: 600, color }),
  card: { background: COLORS.card, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: 24, marginBottom: 24 },
  tableHeader: { padding: '10px 12px', fontSize: 11, fontWeight: 600, color: COLORS.dim, borderBottom: `1px solid ${COLORS.border}`, textTransform: 'uppercase' },
  tableCell: { padding: '12px 12px', fontSize: 13, fontWeight: 400, color: COLORS.muted, borderBottom: `1px solid ${COLORS.border}` },
  badge: (bg, color) => ({ display: 'inline-block', padding: '3px 10px', borderRadius: 20, fontSize: 11, fontWeight: 600, background: bg, color }),
  btn: (bg) => ({ padding: '10px 20px', borderRadius: 8, border: 'none', cursor: 'pointer', fontSize: 13, fontWeight: 600, background: bg, color: COLORS.white }),
  btnOutline: { padding: '10px 20px', borderRadius: 8, border: `1px solid ${COLORS.border}`, cursor: 'pointer', fontSize: 13, fontWeight: 600, background: 'transparent', color: COLORS.muted },
  searchBar: { width: '100%', padding: '10px 12px 10px 36px', borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.bg, color: COLORS.muted, fontSize: 13, outline: 'none' },
  select: { padding: '10px 12px', borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.bg, color: COLORS.muted, fontSize: 13, outline: 'none', cursor: 'pointer' },
};
